### ISSUE TITLE
我把typescript升级到3.9.5报错

### ISSUE THREAD

**Issue by macroswang** [javaLuo/react-admin#10]
你好，我把typescript升级到3.9.5，报很多类似这种错：
ERROR in [at-loader] ./src/models/app.ts:71:22 
    TS2339: Property 'reducerLogout' does not exist on type 'never'.

ERROR in [at-loader] ./src/models/app.ts:84:20 
    TS2339: Property 'reducerUserInfo' does not exist on type 'never'.

ERROR in [at-loader] ./src/models/app.ts:91:48 
    TS2339: Property 'userinfo' does not exist on type 'never'.

ERROR in [at-loader] ./src/models/app.ts:93:56 
    TS2339: Property 'getRoleById' does not exist on type 'never'.

请教一下这种错误要修改修复呢？我也在网上找了半天都没有结果。如果能得到你的回复，将非常感谢

**Comment by javaLuo** [comment]
是的，别升，rematch官方正在处理，下个版本应该就好了：
https://github.com/rematch/rematch/issues/759

如果rematch长期不修复，后面我就换一个redux中间件

**Comment by macroswang** [comment]
感谢回复
