### ISSUE TITLE
"类型“never”上不存在属性“userinfo"之类的这种错误，是怎么回事呀？

### ISSUE THREAD

**Issue by macroswang** [javaLuo/react-admin#11]
你好我在本地运行的时候打开.ts文件出现：
"类型“never”上不存在属性“userinfo"
"类型“never”上不存在属性“setUserinfo"
很多类似的错误，虽然不影响运行，但是看着不舒服，:( 
请问一下这个要怎么解决呀。我本地是使用的vscode工具

**Comment by javaLuo** [comment]
typescript不要升级到3.9.x以上，最好保持在3.8.3
这是rematch的问题，rematch官方仍然在处理

如果rematch长期没有修复，我会考虑换一个redux中间件
