### ISSUE TITLE
顶部的导航标签能换成Tab吗？

### ISSUE THREAD

**Issue by macroswang** [javaLuo/react-admin#13]

**Comment by javaLuo** [comment]
没问题

**Comment by macroswang** [comment]
麻烦问问在哪儿做修改哟？

**Comment by javaLuo** [comment]
现在还不能，得重新做的
有一个`src/components/Bread`组件
得把它改成支持Tab的形式

**Comment by macroswang** [comment]
好的。感谢

**Comment by javaLuo** [comment]
hi,我更新了一下：
在`src/layouts/BasicLayout.tsx`中，
打开第28行注释 和 第134～138行注释，并注释第132行普通面包屑导航， 就会变成Tab导航了：


```javascript
import BreadTab from "@/components/BreadTab"; // Tab方式的导航

<BreadTab
     menus={props.userinfo.menus}
     location={props.location}
     history={props.history}
/>
```

**Comment by macroswang** [comment]
嗯嗯。我也做了一个，还是非常感谢，不过我觉得你的这个路由不合理呀

**Comment by javaLuo** [comment]
哪里不合理呀..
可能我路由的匹配写得比较简单，一些复杂的情况没考虑

**Comment by macroswang** [comment]
主要是我切换tab的时候，每次都要重启加载数据，这样感觉会影响使用

**Comment by macroswang** [comment]
我发现如果不让在切换tab的时候不重新加载数据的话，改动还比较大！

**Comment by javaLuo** [comment]
对啊，切换tab只是切换了路由
我懂你说的那种就得把页面放在Tab页里。
可以用这个缓存需要被缓存的页面：https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md
我之前弄过，后来不记得为什么没了，有空我在弄一下吧。

**Comment by macroswang** [comment]
感谢感谢。你太给力了。。

**Comment by javaLuo** [comment]
嘿，我加了`react-router-cache-route`，
详见`src/layouts/BasicLayout.tsx`中的`CacheRoute`,
