### ISSUE TITLE
请问：在不使用mock的情况下，怎么配置地址呢，可能会存在多个环境，地址需要根据环境改变，类似于转发

### ISSUE THREAD

**Issue by weiqinke** [javaLuo/react-admin#14]

**Comment by javaLuo** [comment]
你可以在`src/util/axios.ts`里根据环境变量设置不同的请求地址
具体我之后写个例子吧

**Comment by javaLuo** [comment]
在代码中用`process.env.NODE_ENV`来区分不同的环境
然后把不同的地址设置给`axios.defaults.baseURL`就好
