### ISSUE TITLE
您好 想请教一下项目中设置了请求头"Content-Type": "application/x-www-form-urlencoded; charset=utf-8",格式，post请求怎么转换为右边中的格式呢

### ISSUE THREAD

**Issue by menglin1997** [javaLuo/react-admin#16]
![image](https://user-images.githubusercontent.com/46981987/94419486-6c24ee00-01b5-11eb-8fc1-bbd900505be6.png)
设置了请求头"Content-Type": "application/x-www-form-urlencoded; charset=utf-8",格式，post请求怎么转换为上图中右边中的格式呢，左边的是实际得到的参数格式   

下图为请求方式
![image](https://user-images.githubusercontent.com/46981987/94419667-adb59900-01b5-11eb-8672-d0b4a43bfe5f.png)

**Comment by javaLuo** [comment]
小伙子听说过qs库吗。

```js
import qs from "qs";

const res : Res = await axios({
  method:'post',
  url: '....',
  data: qs.stringify(params)
});
```

**Comment by menglin1997** [comment]
长见识了 我不是小伙子
