### ISSUE TITLE
项目本地运行，耗时太久了， 5-6分钟才能起起来

### ISSUE THREAD

**Issue by 21haoxingxiu** [javaLuo/react-admin#17]
有没有考虑使用create-react-app这种成熟的脚手架呢

**Comment by javaLuo** [comment]
- - 不是吧，最多2分钟
之前也想过用`create-react-app`，但是有一些限制，比如不能自定义`tsconfig.json`的内容
所以就没弄了

**Comment by YuNode** [comment]
非常耗时, JavaScript heap out of memory ... awesome-typescript-loader切换到ts-loader 会好很多

**Comment by javaLuo** [comment]
现在改成vite了
本地环境是有点慢
