### ISSUE TITLE
dispatch.app.updateUserInfo()缺少参数

### ISSUE THREAD

**Issue by Zddu** [javaLuo/react-admin#20]
你好！这个 dispatch.app.updateUserInfo() 需要rootState，但是我看代码没给这个方法传参呢？运行报错。

**Comment by simononline** [comment]
我也是遇到了这个问题。。

形如这样的错误

ERROR in [at-loader] ./src/pages/System/MenuAdmin/index.tsx:204:26 
    TS2554: Expected 1 arguments, but got 0.

**Comment by cjq456** [comment]
ERROR in [at-loader] ./src/pages/System/MenuAdmin/index.tsx:204:26
TS2554: Expected 1 arguments, but got 0. 这是什么我问题 昨天打开还好好的

**Comment by Zddu** [comment]
已解决

**Comment by javaLuo** [comment]
> ERROR in [at-loader] ./src/pages/System/MenuAdmin/index.tsx:204:26 TS2554: Expected 1 arguments, but got 0. 这是什么我问题 昨天打开还好好的

应该传1个参数，但是你一个多没传。
这个项目我好久没搞了，有空我来review一遍。

如果要用于生产的话，还是建议直接Next.js

**Comment by sunyuboalisa** [comment]
> 昨天

请问这个怎么解决的？

**Comment by DanileQin** [comment]
> > 昨天
> 
> 请问这个怎么解决的？

他其实就是ts报错，你可以尝试修改ts类型，粗暴改为any 以及参数不可传。已经跑起来了

**Comment by sunyuboalisa** [comment]
嗯嗯！ 谢谢大佬！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: Tuesday, February 14, 2023 11:37 AM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [javaLuo/react-admin] dispatch.app.updateUserInfo()缺少参数 (Issue #20)


昨天

请问这个怎么解决的？

他其实就是ts报错，你可以尝试修改ts类型，粗暴改为any 以及参数不可传。已经跑起来了

―

**Comment by javaLuo** [comment]
现在不会了
